version: '3.7'
services:
 server:
  image: server:latest
 app:
  image: client:latest
 db:
  image: postgres
  environment:
    POSTGRES_PASSWORD: docker
    POSTGRES_USER: postgres
    POSTGRES_DB: ticket_tracker
    volumes: /var/lib/postgresql/data
    Ports: 5432:5432
    

  

